name: Build AXON Labs
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compila Navigator
        run: |
          qmk setup -y
          qmk compile -kb axon_labs/vial -km vial
      - name: Salva Firmware
        uses: actions/upload-artifact@v3
        with:
          name: Navigator31_Firmware
          path: ./*.uf2
