name: Build AXON Labs
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Compila Navigator
        run: |
          qmk setup -y
          # Forza QMK a riconoscere la nuova cartella
          qmk compile -kb axon_labs -km vial
      
      - name: Salva Firmware
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Navigator31_Firmware
          path: ./*.uf2
